version: "3"

services:
  svetuz_bot:
    image: mysqluz_backend
    container_name: mysqluz_backend
    build: ./
    restart: always
    volumes:
      - ./:/app
networks:
  default:
    external:
      name: nginx-proxy