# Generated by Django 3.1.7 on 2021-05-09 08:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
