# Generated by Django 3.1.7 on 2021-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='dump_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='dump',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='permissions',
            field=models.IntegerField(choices=[(0, 'SELECT'), (1, 'EXECUTE')]),
        ),
    ]
