# Generated by Django 3.1.7 on 2021-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210502_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='execute_table',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='permissions',
            field=models.IntegerField(choices=[(0, 'SELECT'), (1, 'EXECUTE (INSERT, UPDATE, DELETE)')]),
        ),
    ]
