# Generated by Django 3.1.7 on 2021-05-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210502_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='execute_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(-2, 'IN QUEUE'), (-1, 'RUNNING'), (0, 'JUDGEMENT FAILED'), (1, 'ACCEPTED'), (2, 'WRONG ANSWER')], default=-2),
        ),
    ]
