# Generated by Django 3.1.7 on 2021-05-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-ball',)},
        ),
    ]
